#!/bin/bash

START=121
END=180
HERITABILITY=0.6
C_PROP=0.005
NLOCI=50
NPHENO=50
PHENO_SIM_TYPE="normal" # fixed, bimodal, studentsT, normal
PHENO_RESTRICT="cvar"
CASE_CONTROL_RATIO=1
USE_AGESEX=false
NCAUSAL="2 3 4 5"
NPIMASS="2"
NFINEMAP="2 5 10"
NCAVIARBF="2"
NGEMMA="2"
NBIMBAM="2"
MODEL_PIMASS="linear probit"
MODEL_GEMMA="linear probit"
MUVAR="0"
USE_BLORE_RES=false

# Which methods to run?
bDeleteOld=false
bMakePheno=false
bRegCov=false
bBloreSumm=false
bBloreMeta=false
bSnptest=false
bMeta=false
bFinemap=false
bPimass=false
bGemma=false
bJam=false
bBimbam=false
bCaviarbf=false

#bDeleteOld=true
bMakePheno=true
#bRegCov=true
bBloreSumm=true
bBloreMeta=true
bSnptest=true
bMeta=true
bFinemap=true
#bPimass=true
#bGemma=true
#bJam=true
#bBimbam=true
#bCaviarbf=true
