#!/bin/bash

START=1
END=1
HERITABILITY=0.6
C_PROP=0.005
NSAMPLE_TOT=13082
PHENO_SIM_TYPE="normal" # fixed, bimodal, studentsT, normal
MUVAR="0"
NCAUSAL="2 3"
NPIMASS="2"
MODEL_PIMASS="linear probit"
NFINEMAP="2"
