#!/bin/bash

CURDIR=`pwd`

START=1
END=1
HERITABILITY=0.6
C_PROP=0.005
NSAMPLE_TOT=13082
PHENO_SIM_TYPE="normal" # fixed, bimodal, studentsT, normal

# data directories
BASEDIR="/scratch/sbanerj/quasi_laplace_gwas"
DOSAGEDIR="${BASEDIR}/loci_dosages"
SIMDIR="${BASEDIR}/simulations"
LOCUSNAMES="${BASEDIR}/LOCUSNAMES"
USELOCI="${BASEDIR}/LOCUSNAMES.MAXSNPS"
SAMPLEPREFIX="_QC_age"

# Pipeline directories
SCRIPTDIR="${CURDIR}/../scripts"
MASTER_JOBSUBDIR="${CURDIR}/../bsubfiles"
JOBSUBDIR="${CURDIR}/../jobsubs/${PHENO_SIM_TYPE}_${HERITABILITY}/"
LDBASEDIR="${BASEDIR}/ldmap"
LDMAPDIR="${BASEDIR}/ldmap/weighted"
#LDMAPDIR="${BASEDIR}/ldmap/combined"

# external programs required for the pipeline
SNPTEST="${HOME}/packages/SNPTEST/snptest_v2.5.4-beta3_linux_x86_64_dynamic/snptest_v2.5.4-beta3"
META="${HOME}/packages/META/meta"
LDSTORE="${HOME}/packages/ldstore/ldstore_v1.1_x86_64/ldstore"
BLORE="${HOME}/fine-mapping-SNPs/codebase/b-lore/bin/blore"
PIMASS="${HOME}/packages/pimass/pimass/pimass"
FINEMAP="${HOME}/packages/FINEMAP/finemap_v1.1_x86_64/finemap"
## GEMMA="gemma"
## BIMBAM="${HOME}/packages/BIMBAM/bimbam/bimbam"

# other scripts used in the pipeline
GENINF="${SCRIPTDIR}/genomic_inflation_factor.py"
LDMAP_WEIGHTED="${SCRIPTDIR}/ldmap_weighted.py"
CREATEPHENO="${SCRIPTDIR}/create_phenotype.py"

# Parameters
STUDYNAMES=('G1' 'G2' 'G3' 'G4' 'G5')
STUDYSAMPLES=('2139' '2420' '2472' '2084' '3967')
IFS=$'\r\n' GLOBIGNORE='*' command eval 'LOCIPREFIX=($(cat ${LOCUSNAMES}))'

MUVAR="0"
NCAUSAL="2 3"
NPIMASS="2"
MODEL_PIMASS="linear probit"
NFINEMAP="2"
